name: Python package

on: [push]

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[build]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Build the code
      run: |
        python builder.py
